#!/usr/bin/env bash

VAR_ONE="value\n"    #
VAR_TWO='value\n'
VAR_THREE=value\\n

# command output can be piped to an inline string,
# just like a declared variable using $( ... )

# this line will inject the output of the printf command into the string.
echo This is VAR_ONE: $( printf $VAR_ONE ), VAR_TWO: $( printf $VAR_TWO ), VAR_THREE: $( printf $VAR_THREE )


echo  # -------------------------------


# the output can also be assigned to another variable.
BASH_BIN=$( which bash )

# the which command returns the whole path for the given executable.
echo the bash binary is located at $BASH_BIN
echo the bash binary is located at $( which bash )  # same output as above.

# you can even embed a command inside of another command.
echo the bash binary is located at $( dirname $( which bash ) )
